### ISSUE TITLE
[BUG] Panic when importing json table with numeric field.

### ISSUE THREAD

**Issue by jedvardsson** [nao1215/sqly#43]
**Describe the bug**
Panic when importing json table with numeric field.

**To Reproduce**
1. user.json
```json
[
  {
    "user_id": 1,
    "person_name": "bob"
  }
]
```
2. `sqly --sql "select user_id, person_name from user limit 1" --csv user.json`
3. See error
```
panic: interface conversion: interface {} is float64, not string

goroutine 1 [running]:
github.com/nao1215/sqly/domain/model.(*JSON).ToTable(0x14000092ed0)
	/Users/bob/go/pkg/mod/github.com/nao1215/sqly@v0.5.2/domain/model/json.go:32 +0x5d8
github.com/nao1215/sqly/shell.CommandList.importCommand(0x5?, 0x140000d48c0, {0x1400007e280?, 0x14000026960?, 0x14000026950?})
	/Users/bob/go/pkg/mod/github.com/nao1215/sqly@v0.5.2/shell/import.go:45 +0x50c
github.com/nao1215/sqly/shell.(*Shell).init(0x140000d48c0)
	/Users/bob/go/pkg/mod/github.com/nao1215/sqly@v0.5.2/shell/shell.go:128 +0xb0
github.com/nao1215/sqly/shell.(*Shell).Run(0x140000d48c0)
	/Users/bob/go/pkg/mod/github.com/nao1215/sqly@v0.5.2/shell/shell.go:80 +0x34
main.run({0x140000120f0?, 0x104ea5220?, 0x105273068?})
	/Users/bob/go/pkg/mod/github.com/nao1215/sqly@v0.5.2/main.go:30 +0xb4
main.main()
	/Users/bob/go/pkg/mod/github.com/nao1215/sqly@v0.5.2/main.go:16 +0x34
```

**Expected behavior**
csv output:
```
user_id,person_name
1,bob
```

**Desktop (please complete the following information):**
 - macOS Sonoma 14.4.1 (23E224)
 - go version go1.22.2 darwin/arm64
 - sqly v0.5.2

**Comment by nao1215** [comment]
@jedvardsson 
Thanks for the bug report. It takes time to fix bugs.

**Comment by nao1215** [comment]
Fix this bug at PR https://github.com/nao1215/sqly/pull/47.
